# Generated by Django 4.2 on 2023-04-24 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_products_problem'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='density',
            field=models.CharField(default='all', max_length=250),
        ),
        migrations.AddField(
            model_name='products',
            name='type',
            field=models.CharField(default='all', max_length=250),
        ),
    ]
