# Generated by Django 4.2 on 2023-04-24 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_products_density_products_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='density',
            field=models.CharField(default='thin, medium, thick', max_length=250),
        ),
        migrations.AlterField(
            model_name='products',
            name='type',
            field=models.CharField(default='straight, wavy, curly', max_length=250),
        ),
    ]
